# A configuration file for evaluation on 4 pick and place BEHAVIOR tasks.
# Note that not all baselines can be run at once. Comment things out, change flags,
# and run accordingly.
# Example Usage:
# python scripts/supercloud/launch.py \
# --user wmcclinton \
# --config behavior_pick_place_evaluation.yaml \
# --transfer_local_data \
# --supercloud_dir ~/GitHub/predicators_behavior
---
APPROACHES:
  # oracle: # Oracle
  #   NAME: "oracle"
  # pnad_search: # PNAD search approach.
  #   NAME: "nsrt_learning"
  #   FLAGS:
  #     strips_learner: pnad_search
  cluster_and_intersect:  # Cluster-and-intersect baseline.
    NAME: "nsrt_learning"
    FLAGS:
      strips_learner: "cluster_and_intersect"
      disable_harmlessness_check: True
  cluster_and_search:  # LOFT baseline.
    NAME: "nsrt_learning"
    FLAGS:
      strips_learner: "cluster_and_search"
      disable_harmlessness_check: True
  pred_error:  # Prediction error baseline that optimizes via hill climbing.
    NAME: "nsrt_learning"
    FLAGS: 
      strips_learner: "cluster_and_intersect_sideline_prederror" 
      disable_harmlessness_check: True
  # NOTE: Set the 'plan_only_eval' flag to false when running either
  # of the below GNN approaches.
  # gnn_shooting:  # Model-based GNN option policy baseline.
  #   NAME: "gnn_option_policy"
  # Model-free GNN option policy baseline.
  #   NAME: "gnn_option_policy"
  #   FLAGS:
  #     gnn_option_policy_solve_with_shooting: False
ENVS:
  satellites-simple:
    NAME: "satellites_simple"
  repeated-nextto-painting:
    NAME: "repeated_nextto_painting"

ARGS: {}
FLAGS:  # general flags
  # NOTE: set below to False when using GNN's!
  plan_only_eval: True #False
  sesame_task_planner: fdsat
  num_train_tasks: 50
  num_test_tasks: 0
START_SEED: 456
NUM_SEEDS: 10
USE_GPU: True
