# A configuration file for 20 BEHAVIOR tasks.
---
APPROACHES:
  my-oracle:
    NAME: "oracle"
    FLAGS:
      plan_only_eval: True
      sesame_task_planner: fdopt
ENVS:
  picking_up_trash-Wainscott_0_int:
    NAME: "behavior"
    FLAGS:
      behavior_train_scene_name: Wainscott_0_int
      behavior_test_scene_name: Wainscott_0_int
      behavior_task_list: "[picking_up_trash]"
      behavior_option_model_eval: True
  polishing_furniture-Rs_int:
    NAME: "behavior"
    FLAGS:
      behavior_train_scene_name: Rs_int
      behavior_test_scene_name: Rs_int
      behavior_task_list: "[polishing_furniture]"
      behavior_option_model_eval: True
  polishing_silver-Wainscott_0_int:
    NAME: "behavior"
    FLAGS:
      behavior_train_scene_name: Wainscott_0_int
      behavior_test_scene_name: Wainscott_0_int
      behavior_task_list: "[polishing_silver]"
      behavior_option_model_eval: True
  putting_leftovers_away-Ihlen_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_train_scene_name: Ihlen_1_int
      behavior_test_scene_name: Ihlen_1_int
      behavior_task_list: "[putting_leftovers_away]"
      behavior_option_model_eval: True
  re-shelving_library_books-Pomaria_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_train_scene_name: Pomaria_1_int
      behavior_test_scene_name: Pomaria_1_int
      behavior_task_list: "[re-shelving_library_books]"
      behavior_option_model_eval: True
  sorting_books-Pomaria_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_train_scene_name: Pomaria_1_int
      behavior_test_scene_name: Pomaria_1_int
      behavior_task_list: "[sorting_books]"
      behavior_option_model_eval: True
  throwing_away_leftovers-Ihlen_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_train_scene_name: Ihlen_1_int
      behavior_test_scene_name: Ihlen_1_int
      behavior_task_list: "[throwing_away_leftovers]"
      behavior_option_model_eval: True
  unpacking_suitcase-Ihlen_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_train_scene_name: Ihlen_1_int
      behavior_test_scene_name: Ihlen_1_int
      behavior_task_list: "[unpacking_suitcase]"
      behavior_option_model_eval: True
ARGS: {}
FLAGS:  # general flags
  offline_data_planning_timeout: 1000.0
  timeout: 1000.0
  horizon: 1000
  behavior_override_learned_samplers: True
  behavior_ignore_discover_failures: True
  create_training_dataset: True
  num_train_tasks: 5
  num_test_tasks: 5
START_SEED: 465
NUM_SEEDS: 10
USE_GPU: False
