# A configuration file for 20 BEHAVIOR tasks.
---
APPROACHES:
  my-oracle:
    NAME: "oracle"
    FLAGS:
      plan_only_eval: True
      sesame_task_planner: fdopt
ENVS:
  bringing_in_wood-Wainscott_0_int:
    NAME: "behavior"
    FLAGS:
      behavior_train_scene_name: Wainscott_0_int
      behavior_test_scene_name: Wainscott_0_int
      behavior_task_list: "[bringing_in_wood]"
      behavior_option_model_eval: True
  packing_food_for_work-Wainscott_0_int:
    NAME: "behavior"
    FLAGS:
      behavior_train_scene_name: Wainscott_0_int
      behavior_test_scene_name: Wainscott_0_int
      behavior_task_list: "[packing_food_for_work]"
      behavior_option_model_eval: True
  putting_away_Christmas_decorations-Merom_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_train_scene_name: Merom_1_int
      behavior_test_scene_name: Merom_1_int
      behavior_task_list: "[putting_away_Christmas_decorations]"
      behavior_option_model_eval: True
  putting_away_Halloween_decorations-Merom_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_train_scene_name: Merom_1_int
      behavior_test_scene_name: Merom_1_int
      behavior_task_list: "[putting_away_Halloween_decorations]"
      behavior_option_model_eval: True
ARGS: {}
FLAGS:  # general flags
  offline_data_planning_timeout: 1000.0
  timeout: 1000.0
  horizon: 1000
  behavior_override_learned_samplers: True
  behavior_ignore_discover_failures: True
  create_training_dataset: True
  num_train_tasks: 0
  num_test_tasks: 5
START_SEED: 465
NUM_SEEDS: 10
USE_GPU: False
