# A configuration file for 20 BEHAVIOR tasks.
---
APPROACHES:
  my-oracle:
    NAME: "oracle"
    FLAGS:
      plan_only_eval: True
      sesame_task_planner: fdopt
ENVS:
  setting_mousetraps-Benevolence_2_int:
    NAME: "behavior"
    FLAGS:
      behavior_train_scene_name: Benevolence_2_int
      behavior_test_scene_name: Benevolence_2_int
      behavior_task_list: "[setting_mousetraps]"
      behavior_option_model_eval: True
  cleaning_a_car-Ihlen_0_int:
    NAME: "behavior"
    FLAGS:
      behavior_train_scene_name: Ihlen_0_int
      behavior_test_scene_name: Ihlen_0_int
      behavior_task_list: "[cleaning_a_car]"
      behavior_option_model_eval: True
  installing_a_fax_machine-Pomaria_0_int:
    NAME: "behavior"
    FLAGS:
      behavior_train_scene_name: Pomaria_0_int
      behavior_test_scene_name: Pomaria_0_int
      behavior_task_list: "[installing_a_fax_machine]"
      behavior_option_model_eval: True
  loading_the_dishwasher-Pomaria_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_train_scene_name: Pomaria_1_int
      behavior_test_scene_name: Pomaria_1_int
      behavior_task_list: "[loading_the_dishwasher]"
      behavior_option_model_eval: True
  re-shelving_library_books-Pomaria_1_int:
    NAME: "behavior"
    FLAGS:
      behavior_train_scene_name: Pomaria_1_int
      behavior_test_scene_name: Pomaria_1_int
      behavior_task_list: "[re-shelving_library_books]"
      behavior_option_model_eval: True
ARGS: {}
FLAGS:  # general flags
  offline_data_planning_timeout: 1000.0
  timeout: 1000.0
  horizon: 1000
  behavior_override_learned_samplers: True
  behavior_ignore_discover_failures: True
  create_training_dataset: True
  num_train_tasks: 5
  num_test_tasks: 5
START_SEED: 465
NUM_SEEDS: 10
USE_GPU: False
