# An example configuration file.
---
APPROACHES:
  astar-oracle:  # used in constructing the experiment ID
    NAME: "oracle"
    FLAGS: {}
  fd-oracle:  # used in constructing the experiment ID
    NAME: "oracle"
    FLAGS:
      sesame_task_planner: fdopt
ENVS:
  cluttered-table-default-settings:  # used in constructing the experiment ID
    NAME: "cluttered_table"
    FLAGS: {}
ARGS:
  - "debug"
FLAGS:  # general flags
  num_train_tasks: 0
  num_test_tasks: 50
START_SEED: 456
NUM_SEEDS: 10
