#!/bin/bash

python predicators/main.py --env behavior --approach oracle --option_model_name oracle_behavior --num_train_tasks 0 --num_test_tasks 1 --behavior_train_scene_name Benevolence_1_int --behavior_test_scene_name Benevolence_1_int --behavior_task_list "[boxing_books_up_for_storage]" --seed 0 --offline_data_planning_timeout 2000.0 --timeout 2000.0 --behavior_option_model_eval True --behavior_mode iggui --behavior_option_model_rrt True --behavior_save_video True --sesame_task_planner fdopt
# python predicators/main.py --env behavior --approach oracle --option_model_name oracle_behavior --num_train_tasks 0 --num_test_tasks 1 --behavior_train_scene_name Merom_1_int --behavior_test_scene_name Merom_1_int --behavior_task_list "[collect_misplaced_items]" --seed 0 --offline_data_planning_timeout 2000.0 --timeout 2000.0 --behavior_option_model_eval True --behavior_mode iggui --behavior_option_model_rrt True --behavior_save_video True --sesame_task_planner fdopt
python predicators/main.py --env behavior --approach oracle --option_model_name oracle_behavior --num_train_tasks 0 --num_test_tasks 1 --behavior_train_scene_name Benevolence_2_int --behavior_test_scene_name Benevolence_2_int --behavior_task_list "[collecting_aluminum_cans]" --seed 0 --offline_data_planning_timeout 2000.0 --timeout 2000.0 --behavior_option_model_eval True --behavior_mode iggui --behavior_option_model_rrt True --behavior_save_video True --sesame_task_planner fdopt
# python predicators/main.py --env behavior --approach oracle --option_model_name oracle_behavior --num_train_tasks 0 --num_test_tasks 1 --behavior_train_scene_name Pomaria_0_int --behavior_test_scene_name Pomaria_0_int --behavior_task_list "[locking_every_door]" --seed 0 --offline_data_planning_timeout 2000.0 --timeout 2000.0 --behavior_option_model_eval True --behavior_mode iggui --behavior_option_model_rrt True --behavior_save_video True --sesame_task_planner fdopt
python predicators/main.py --env behavior --approach oracle --option_model_name oracle_behavior --num_train_tasks 0 --num_test_tasks 1 --behavior_train_scene_name Rs_int --behavior_test_scene_name Rs_int --behavior_task_list "[locking_every_window]" --seed 0 --offline_data_planning_timeout 2000.0 --timeout 2000.0 --behavior_option_model_eval True --behavior_mode iggui --behavior_option_model_rrt True --behavior_save_video True --sesame_task_planner fdopt
# python predicators/main.py --env behavior --approach oracle --option_model_name oracle_behavior --num_train_tasks 0 --num_test_tasks 1 --behavior_train_scene_name Pomaria_2_int --behavior_test_scene_name Pomaria_2_int --behavior_task_list "[opening_packages]" --seed 0 --offline_data_planning_timeout 2000.0 --timeout 2000.0 --behavior_option_model_eval True --behavior_mode iggui --behavior_option_model_rrt True --behavior_save_video True --sesame_task_planner fdopt
python predicators/main.py --env behavior --approach oracle --option_model_name oracle_behavior --num_train_tasks 0 --num_test_tasks 1 --behavior_train_scene_name Pomaria_2_int --behavior_test_scene_name Pomaria_2_int --behavior_task_list "[opening_presents]" --seed 0 --offline_data_planning_timeout 2000.0 --timeout 2000.0 --behavior_option_model_eval True --behavior_mode iggui --behavior_option_model_rrt True --behavior_save_video True --sesame_task_planner fdopt
# python predicators/main.py --env behavior --approach oracle --option_model_name oracle_behavior --num_train_tasks 0 --num_test_tasks 1 --behavior_train_scene_name Wainscott_0_int --behavior_test_scene_name Wainscott_0_int --behavior_task_list "[picking_up_trash]" --seed 0 --offline_data_planning_timeout 2000.0 --timeout 2000.0 --behavior_option_model_eval True --behavior_mode iggui --behavior_option_model_rrt True --behavior_save_video True --sesame_task_planner fdopt
python predicators/main.py --env behavior --approach oracle --option_model_name oracle_behavior --num_train_tasks 0 --num_test_tasks 1 --behavior_train_scene_name Ihlen_1_int --behavior_test_scene_name Ihlen_1_int --behavior_task_list "[putting_leftovers_away]" --seed 0 --offline_data_planning_timeout 2000.0 --timeout 2000.0 --behavior_option_model_eval True --behavior_mode iggui --behavior_option_model_rrt True --behavior_save_video True --sesame_task_planner fdopt
# python predicators/main.py --env behavior --approach oracle --option_model_name oracle_behavior --num_train_tasks 0 --num_test_tasks 1 --behavior_train_scene_name Pomaria_1_int --behavior_test_scene_name Pomaria_1_int --behavior_task_list "[sorting_books]" --seed 0 --offline_data_planning_timeout 2000.0 --timeout 2000.0 --behavior_option_model_eval True --behavior_mode iggui --behavior_option_model_rrt True --behavior_save_video True --sesame_task_planner fdopt
python predicators/main.py --env behavior --approach oracle --option_model_name oracle_behavior --num_train_tasks 0 --num_test_tasks 1 --behavior_train_scene_name Ihlen_1_int --behavior_test_scene_name Ihlen_1_int --behavior_task_list "[throwing_away_leftovers]" --seed 0 --offline_data_planning_timeout 2000.0 --timeout 2000.0 --behavior_option_model_eval True --behavior_mode iggui --behavior_option_model_rrt True --behavior_save_video True --sesame_task_planner fdopt
# python predicators/main.py --env behavior --approach oracle --option_model_name oracle_behavior --num_train_tasks 0 --num_test_tasks 1 --behavior_train_scene_name Ihlen_1_int --behavior_test_scene_name Ihlen_1_int --behavior_task_list "[unpacking_suitcase]" --seed 0 --offline_data_planning_timeout 2000.0 --timeout 2000.0 --behavior_option_model_eval True --behavior_mode iggui --behavior_option_model_rrt True --behavior_save_video True --sesame_task_planner fdopt
python predicators/main.py --env behavior --approach oracle --option_model_name oracle_behavior --num_train_tasks 0 --num_test_tasks 1 --behavior_train_scene_name Ihlen_0_int --behavior_test_scene_name Ihlen_0_int --behavior_task_list "[cleaning_a_car]" --seed 0 --offline_data_planning_timeout 2000.0 --timeout 2000.0 --behavior_option_model_eval True --behavior_mode iggui --behavior_option_model_rrt True --behavior_save_video True --sesame_task_planner fdopt
# python predicators/main.py --env behavior --approach oracle --option_model_name oracle_behavior --num_train_tasks 0 --num_test_tasks 1 --behavior_train_scene_name Benevolence_2_int --behavior_test_scene_name Benevolence_2_int --behavior_task_list "[setting_mousetraps]" --seed 0 --offline_data_planning_timeout 2000.0 --timeout 2000.0 --behavior_option_model_eval True --behavior_mode iggui --behavior_option_model_rrt True --behavior_save_video True --sesame_task_planner fdopt
python predicators/main.py --env behavior --approach oracle --option_model_name oracle_behavior --num_train_tasks 0 --num_test_tasks 1 --behavior_train_scene_name Pomaria_1_int --behavior_test_scene_name Pomaria_1_int --behavior_task_list "[re-shelving_library]" --seed 0 --offline_data_planning_timeout 2000.0 --timeout 2000.0 --behavior_option_model_eval True --behavior_mode iggui --behavior_option_model_rrt True --behavior_save_video True --sesame_task_planner fdopt